//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_Final.MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Venta
    {
        public int Id_Venta { get; set; }
        public Nullable<int> Id_UsuariosFK { get; set; }
        public Nullable<int> Id_ProductoFK { get; set; }
        public Nullable<int> Cantidad { get; set; }
        public Nullable<decimal> totalVenta { get; set; }
        public System.DateTime fechaVenta { get; set; }
    
        public virtual Productos Productos { get; set; }
        public virtual Usuarios Usuarios { get; set; }
    }
}
